---
- name: Download multiple files using get_url
  hosts: linux_machines
  become: yes
  tasks:
    - name: Download files from multiple URLs
      ansible.builtin.get_url:
      ansible.builtin.get_url:  
        url: "{{ item.url }}"
        dest:  "{{ item.dest }}"
        mode: '0644'
        owner: tech
      loop:
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/eb8d76c6-f362-4354-ad8c-cdfd1d8390a8/public/windows11.0-kb5077181-x64_33d38563662e659ceb84fb8b65aa05ce5876f5a4.msu", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/d8b7f92b-bd35-4b4c-96e5-46ce984b31e0/public/windows11.0-kb5043080-x64_953449672073f8fb99badb4cc6d5d7849b9c83e8.msu", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/f263aa64-f367-42f0-9cad-328f342b93f7/public/windows11.0-kb5043080-arm64_df540a05f9b118e339c5520f4090bb5d450f090b.msu", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/b9e73ab9-5568-42bf-bc78-6d67da98bcf6/public/windows11.0-kb5077181-arm64_dfd4941f923abb6ece5c224fd953f227aace71b8.msu", dest: "/home/tech/REST_UPDATES" }

