---
- name: Download multiple files using get_url
  hosts: linux_machines
  become: yes
  tasks:
    - name: Download files from multiple URLs
      ansible.builtin.get_url:
      ansible.builtin.get_url:  
        url: "{{ item.url }}"
        dest:  "{{ item.dest }}"
        mode: '0644'
        owner: tech
      loop:
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/uprl/2025/12/windows-kb890830-v5.138_57fca59c88ecd7eeb0ce317823e8e7a2510a0580.exe", dest: "/home/tech" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2025/12/updateplatform.arm64fre_be48cea7150940070027bef828bdc3d1ffd5c930.exe", dest: "/home/tech" }
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/3541f8bc-7744-458c-801e-805387fe2943/public/windows11.0-kb5066131-arm64-ndp481_3beead8035fa38f397904cc3f407f234cc7e1c13.msu", dest: "/home/tech" }
