---
- name: Download multiple files using get_url
  hosts: linux_machines
  become: yes
  tasks:
    - name: Download files from multiple URLs
      ansible.builtin.get_url:
      ansible.builtin.get_url:  
        url: "{{ item.url }}"
        dest:  "{{ item.dest }}"
        mode: '0644'
        owner: tech
      loop:
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/6a205b6d-707b-4860-a00a-f00fa5be9e6f/public/windows11.0-kb5071417-arm64_0fbcfe5586583fb737a8b1347ebdc3aeb7b92beb.msu", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/7e819a39-0e82-4f80-bacb-71b3f6632f3d/public/windows11.0-kb5071417-x64_e19910906e0392876385744f955c05495a4fb16c.msu", dest: "/home/tech/REST_UPDATES" }

