---
- name: Download multiple files using get_url
  hosts: linux_machines
  become: yes
  tasks:
    - name: Download files from multiple URLs
      ansible.builtin.get_url:
      ansible.builtin.get_url:  
        url: "{{ item.url }}"
        dest:  "{{ item.dest }}"
        mode: '0644'
        owner: tech
      loop:
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/07012b06-1909-470c-ad1c-b3c542a02527/public/windows11.0-kb5075941-x64_550053e227ce7d6e109108e05aa816eb8cd76a91.msu", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/a47993b8-deff-4eac-b120-9002344b60bf/public/windows11.0-kb5076124-x64_f5a481145d739c5569e4e9e742017366a3eb43c3.cab", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/8283a948-0c07-46e2-9386-89e06e15c97c/public/windows11.0-kb5077374-x64_3bcad59a0c1ba159a9e8f19b75e96c507373860f.cab", dest: "/home/tech/REST_UPDATES" }
