---
- name: Search and download Windows updates without installing them
  hosts: rest_laptops
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: downloaded
