---
- name: Download multiple files using get_url
  hosts: linux_machines
  become: yes
  tasks:
    - name: Download files from multiple URLs
      ansible.builtin.get_url:
      ansible.builtin.get_url:  
        url: "{{ item.url }}"
        dest:  "{{ item.dest }}"
        mode: '0644'
        owner: tech
      loop:
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_6103d9f6bf95c772c8b7ee89aee370cdca4642f8.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_a8a14f2a3dfee79379412cbdec191d46353a7e4a.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_a8a14f2a3dfee79379412cbdec191d46353a7e4a.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_6103d9f6bf95c772c8b7ee89aee370cdca4642f8.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_a8a14f2a3dfee79379412cbdec191d46353a7e4a.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_6103d9f6bf95c772c8b7ee89aee370cdca4642f8.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_a8a14f2a3dfee79379412cbdec191d46353a7e4a.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_6103d9f6bf95c772c8b7ee89aee370cdca4642f8.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_a8a14f2a3dfee79379412cbdec191d46353a7e4a.exe", dest: "/home/tech/REST_UPDATES" }
        - { url: "https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/defu/2024/01/mpsigstub_a8a14f2a3dfee79379412cbdec191d46353a7e4a.exe", dest: "/home/tech/REST_UPDATES" }

        

