---
- name: Search and download Windows updates without installing them
  hosts: windows
  become: false
  gather_facts: false
  vars:
    ansible_user: ansible
    ansible_password: Z3i0pZS3B5YPjg3p5cIPVHd/KUo5FKDS26FDQdsirSY=
    ansible_connection: winrm
    ansible_remote_tmp: C:\Users\ansible\tmp\.ansible\tmp
  tasks:
    - name: Search and download
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: downloaded
        log_path: '%USERPROFILE%\ansible.txt'
