---
- name: install win updates locally
  hosts: windows
  become: false
  gather_facts: true
  vars:
    ansible_user: ansible
    ansible_password: Z3i0pZS3B5YPjg3p5cIPVHd/KUo5FKDS26FDQdsirSY=
    ansible_connection: winrm
  tasks: 
    - name: Install Windows update from local file 1
      ansible.windows.win_package:
        path: C:\updateplatform.arm64fre_be48cea7150940070027bef828bdc3d1ffd5c930.exe

