---
- name: install win updates locally
  hosts: windows
  become: yes
  become_method: runas
  become_user: hcso
  gather_facts: false
  vars:
    ansible_user: ansible
    ansible_password: Z3i0pZS3B5YPjg3p5cIPVHd/KUo5FKDS26FDQdsirSY=
    ansible_connection: winrm
  tasks: 
    - name: Install Windows update from local file
      ansible.windows.win_package:
        path: \\10.21.1.185\rest_windows_updates\REST_UPDATES\windows11.0-kb5075907-x64_3c0bd7edec22ad2cc4d629ee155994e3aa9fbf35.cab
  tasks: 
    - name: Install Windows update from local file
      ansible.windows.win_package:
        path: \\10.21.1.185\rest_windows_updates\REST_UPDATES\windows11.0-kb5077373-x64_8c2eeb32cace3652438ea1e53f15beccd7b1f70e.cab
        arguments: /quiet /norestart
