---
- name: install win updates locally
  hosts: windows
  become: yes
  become_method: runas
  become_user: hcso
  gather_facts: true
  vars:
    ansible_user: ansible
    ansible_password: Z3i0pZS3B5YPjg3p5cIPVHd/KUo5FKDS26FDQdsirSY=
    ansible_connection: winrm
  tasks: 
    - name: Install Windows update from local file
      ansible.windows.win_package:
        path: \\10.21.1.185\rest_updates\REST_UPDATES\updateplatform.arm64fre_be48cea7150940070027bef828bdc3d1ffd5c930.exe
        arguments: /quiet /norestart
