---
- name: install win updates locally
  hosts: windows
  become: false
  gather_facts: true
  vars:
    ansible_user: ansible
    ansible_password: Z3i0pZS3B5YPjg3p5cIPVHd/KUo5FKDS26FDQdsirSY=
    ansible_connection: winrm
  tasks: 
    - name: Install Windows update from local file
      ansible.windows.win_package:
        path: C:\windows-kb890830-v5.138_57fca59c88ecd7eeb0ce317823e8e7a2510a0580.exe
        arguments: /quiet /norestart
