---
- name: install win updates locally
  hosts: windows
  become: false
  gather_facts: true
  vars:
    ansible_user: ansible
    ansible_password: Z3i0pZS3B5YPjg3p5cIPVHd/KUo5FKDS26FDQdsirSY=
    ansible_connection: winrm
  tasks: 
    - name: Install Windows update from local file
      ansible.windows.win_package:
        path: C:\windows11.0-kb5066131-arm64-ndp481_3beead8035fa38f397904cc3f407f234cc7e1c13.msu
        arguments: /quiet /norestart
