---
- name: install win updates locally
  hosts: windows
  become: yes
  become_method: runas
  become_user: ansible
  gather_facts: true
  vars:
    ansible_user: hcso
    ansible_password: radiotech
    ansible_connection: winrm
  tasks: 
    - name: Install Windows update from local file
      ansible.windows.win_package:
        path: \\10.21.1.185\rest_updates\REST_UPDATES\securityhealthsetup_1528aebc5e90a333bf0f8a3f0d98b458311581fa.exe
        arguments: /quiet /norestart
