---
- name: Update and upgrade Ubuntu servers
  hosts: linux_machines        # Define your inventory group in hosts file
  become: no                  # Run tasks with sudo privileges
  gather_facts: yes

  vars:
    reboot_if_needed: true     # Set to false if you don't want automatic reboots

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600   # Only update if cache is older than 1 hour

    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if needed
      reboot:
        msg: "Reboot initiated by Ansible after updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when:
        - reboot_if_needed
        - reboot_required.stat.exists
