---
- name: windows rolling update
  hosts: rest_laptops
  tasks:
    - name: Install all critical and security updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: installed
        reboot: true
        log_path: '%USERPROFILE%\ansible.txt'
